# Generated by Django 3.1.7 on 2021-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='comments',
            field=models.CharField(default='Blank', max_length=500),
            preserve_default=False,
        ),
    ]
