# Generated by Django 3.1.7 on 2021-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
